language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t chefanitha/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chefanitha/docker-react npm run test -- --coverage